bgp_configs = {
    'R1': [
        'router bgp 1',
        'bgp router-id 1.1.1.1',
        'neighbor 4.4.4.4 remote-as 1',
        'neighbor 4.4.4.4 update-source Loopback0',
        'address-family vpnv4',
        'neighbor 4.4.4.4 activate',
        'neighbor 4.4.4.4 send-community extended',
        'exit-address-family',
    ],
    'R2': [
        'router bgp 1',
        'bgp router-id 2.2.2.2',
        'neighbor 4.4.4.4 remote-as 1',
        'neighbor 4.4.4.4 update-source Loopback0',
        'address-family vpnv4',
        'neighbor 4.4.4.4 activate',
        'neighbor 4.4.4.4 send-community extended',
        'exit-address-family',
    ],
    'R3': [
        'router bgp 1',
        'bgp router-id 3.3.3.3',
        'neighbor 4.4.4.4 remote-as 1',
        'neighbor 4.4.4.4 update-source Loopback0',
        'address-family vpnv4',
        'neighbor 4.4.4.4 activate',
        'neighbor 4.4.4.4 send-community extended',
        'exit-address-family',
    ],
    'R4': [
        'router bgp 1',
        'bgp router-id 4.4.4.4',
        
        'neighbor 1.1.1.1 remote-as 1',
        'neighbor 1.1.1.1 update-source Loopback0',
        'neighbor 2.2.2.2 remote-as 1',
        'neighbor 2.2.2.2 update-source Loopback0',
        'neighbor 3.3.3.3 remote-as 1',
        'neighbor 3.3.3.3 update-source Loopback0',
        'neighbor 5.5.5.5 remote-as 1',
        'neighbor 5.5.5.5 update-source Loopback0',
        'neighbor 6.6.6.6 remote-as 1',
        'neighbor 6.6.6.6 update-source Loopback0',
        
        'address-family ipv4',
        'neighbor 1.1.1.1 activate',
        'neighbor 2.2.2.2 activate',
        'neighbor 3.3.3.3 activate',
        'neighbor 5.5.5.5 activate',
        'neighbor 6.6.6.6 activate',
        'exit-address-family',

        'address-family vpnv4',
        'neighbor 1.1.1.1 activate',
        'neighbor 1.1.1.1 send-community extended',
        'neighbor 1.1.1.1 route-reflector-client',
        'neighbor 2.2.2.2 activate',
        'neighbor 2.2.2.2 send-community extended',
        'neighbor 2.2.2.2 route-reflector-client',
        'neighbor 3.3.3.3 activate',
        'neighbor 3.3.3.3 send-community extended',
        'neighbor 3.3.3.3 route-reflector-client',
        'neighbor 5.5.5.5 activate',
        'neighbor 5.5.5.5 send-community extended',
        'neighbor 5.5.5.5 route-reflector-client',
        'neighbor 6.6.6.6 activate',
        'neighbor 6.6.6.6 send-community extended',
        'neighbor 6.6.6.6 route-reflector-client',
        'exit-address-family',
    ],
    'PE-1': [
        'router bgp 1',
        'bgp router-id 5.5.5.5',
        'neighbor 4.4.4.4 remote-as 1',
        'neighbor 4.4.4.4 update-source Loopback0',
        'address-family vpnv4',
        'neighbor 4.4.4.4 activate',
        'neighbor 4.4.4.4 send-community extended',
        'exit-address-family',
    ],
    'PE-2': [
        'router bgp 1',
        'bgp router-id 6.6.6.6',
        'neighbor 4.4.4.4 remote-as 1',
        'neighbor 4.4.4.4 update-source Loopback0',
        'address-family vpnv4',
        'neighbor 4.4.4.4 activate',
        'neighbor 4.4.4.4 send-community extended',
        'exit-address-family',
    ],
    
}