ospf_configs = {
    'R1': [
        'router ospf 1',
        'router-id 1.1.1.1',
        'passive-interface Loopback0',
        'int f0/0',
        'ip ospf 1 area 0',
        'int f1/0',
        'ip ospf 1 area 0',
        'int f2/0',
        'ip ospf 1 area 0',
        'int lo0',
        'ip ospf 1 area 0',
        'exit',
    ],
    'R2': [
        'router ospf 1',
        'router-id 2.2.2.2',
        'passive-interface Loopback0',
        'int f0/0',
        'ip ospf 1 area 0',
        'int f1/0',
        'ip ospf 1 area 0',
        'int lo0',
        'ip ospf 1 area 0',
        'exit',
    ],
    'R3': [
        'router ospf 1',
        'router-id 3.3.3.3',
        'passive-interface Loopback0',
        'int f0/0',
        'ip ospf 1 area 0',
        'int f1/0',
        'ip ospf 1 area 0',
        'int f2/0',
        'ip ospf 1 area 0',
        'int lo0',
        'ip ospf 1 area 0',
        'exit',
    ],
    'R4': [
        'router ospf 1',
        'router-id 4.4.4.4',
        'passive-interface Loopback0',
        'int f0/0',
        'ip ospf 1 area 0',
        'int f1/0',
        'ip ospf 1 area 0',
        'int lo0',
        'ip ospf 1 area 0',
        'exit',
    ],
    'PE-1': [
        'router ospf 1',
        'router-id 5.5.5.5',
        'passive-interface Loopback0',
        'int f2/0',
        'ip ospf 1 area 0',
        'int lo0',
        'ip ospf 1 area 0',
        'exit',
    ],
    'PE-2': [
        'router ospf 1',
        'router-id 6.6.6.6',
        'passive-interface Loopback0',
        'int f2/0',
        'ip ospf 1 area 0',
        'int lo0',
        'ip ospf 1 area 0',
        'exit',
    ],
}